name: Docker

on:
  push:
    branches:
    - master

env:
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        version:
        - "5.3.0"
        include:
        - version: "5.3.0"
          latest: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: librespeed/speedtest
        ref: ${{ matrix.version }}

    - name: Configure
      id: config
      run: |-
        NPROC=$(nproc)

        echo "NPROC=$((NPROC*2+1))" >> $GITHUB_ENV
        echo "NPROC=$((NPROC*2+1))" >> $GITHUB_OUTPUT

        echo "image-owner=${{ github.repository_owner }}" >> $GITHUB_OUTPUT
        echo "image-name=${GITHUB_REPOSITORY#*/docker-}" >> $GITHUB_OUTPUT

    - name: Setup - QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ matrix.platforms || env.PLATFORMS || 'linux/amd64' }}

    - name: Setup - Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup - Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup - Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |-
          ${{ steps.config.outputs.image-owner }}/${{ steps.config.outputs.image-name }}
          ghcr.io/${{ steps.config.outputs.image-owner }}/${{ steps.config.outputs.image-name }}
        flavor: |-
          latest=${{ !!matrix.latest }}
        tags: |-
          type=semver,pattern={{major}}.{{minor}},value=${{ matrix.version }}
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ matrix.version }}

    - name: Build
      uses: docker/build-push-action@v5
      id: build
      with:
        context: .
        build-args: |
          version=${{ matrix.version }}
        push: true
        platforms: ${{ matrix.platforms || env.PLATFORMS || 'linux/amd64' }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
